[package]
name = "vk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"
ash = "0.33.3"
ash-window = "0.7"
raw-window-handle = "0.3"
num = "0.4.0"
